app:
  name: "Binance Grid Trading Backend"
  version: "1.0.0"
  log_level: "INFO"

database:
  path: "data/grid_trading.db"
  echo: false

binance:
  api_key: null
  api_secret: null
  testnet: true
  binance_url: "https://testnet.binance.vision"
  websocket_url: "wss://stream.testnet.binance.vision"
